### PR TITLE
Fix compiler warnings

### LINKED ISSUE #8: Fix compiler warnings
Currently, we see a ton of compiler warnings in release mode due to having quite a few lines like:
```C++
// We, see a warning that iParam is unused in release mode
int iParam = params.size() - paramsStart;
assert(iParam == nParams);
```

We should fix this by doing something like:

```C++
assert((params.size() - paramsStart) == nParams);
```

### PR DESCRIPTION
**Pull request by rcarson3**
This closes #8 and fixes all of the compiler warnings that we were seeing in regards to unused variables in release mode.

### CODE REVIEW

File: src/ecmech/ECMech_evptn.h [hunk 1]
```diff
@@ -81,15 +80,18 @@ namespace ecmech {
...
                int paramsStart = params.size();
+#endif
 
                params.push_back(_c11);
                params.push_back(_c12);
                params.push_back(_c44);
 
-               int iParam = params.size() - paramsStart;
-               assert(iParam == nParams);
+#ifdef ECMECH_DEBUG
```
Comment (nrbarton) [inline src/ecmech/ECMech_evptn.h:92]: Here and elsewhere, do we really need to put these assert checks inside of ECMECH_DEBUG ifdefs? These are not performance-critical parts of the code, and I would be tempted to have the asserts active even in non-debug builds unless they are causing some kind of trouble.

File: src/ecmech/ECMech_slipgeom.h [hunk 2]
```diff
@@ -99,20 +99,18 @@ namespace ecmech {
             fillFromMS(this->_P_ref_vec, this->_Q_ref_vec,
                        mVecs, sVecs, this->nslip);
 
-            int iParam = parsIt - params.begin();
-            assert(iParam == nParams);
+            // assert((parsIt - params.begin()) == nParams);
```
Comment (nrbarton) [inline src/ecmech/ECMech_slipgeom.h]: Why did this one and some of the others in this file get commented-out?

**Review by nrbarton — COMMENTED** [review]
I made some comments to consider.

File: src/ecmech/ECMech_evptn.h (hunk 1 above)
Comment (rcarson3) [reply src/ecmech/ECMech_evptn.h:92]: So, the asserts are only active/compiled in debug builds. In release builds, the assert isn't compiled and so the check is never done. It's the reason why I hid this behind the ECMECH_DEBUG define so the compiler wouldn't complain about some variables never being used. If we want this assert active for all builds then we'll want to look at another function to do this.

File: src/ecmech/ECMech_slipgeom.h (hunk 2 above)
Comment (rcarson3) [reply src/ecmech/ECMech_slipgeom.h]: At least for these ones, it was because there were no inputs. So, the check was unnecessary. I think I'd planned on removing these before the PR was pulled in but just commented them out for now for review process.

File: src/ecmech/ECMech_evptn.h (hunk 1 above)
Comment (nrbarton) [reply src/ecmech/ECMech_evptn.h:92]: Got it. I educated myself a bit more on assert, and see what you mean. We should just make sure we test with debug builds often enough.

File: src/ecmech/ECMech_slipgeom.h (hunk 2 above)
Comment (nrbarton) [reply src/ecmech/ECMech_slipgeom.h]: For the review, please put them into whatever final condition is appropriate. Stray "dead code" can be confusing. I would be tempted to leave them in and put them in ifdefs like the others just to keep things consistent, in case some of the functions end up pulling parameters in later modifications, or getting used as examples when people are writing alternative implementations.

Comment (rcarson3) [reply src/ecmech/ECMech_slipgeom.h]: @nrbarton so I ended up just removing the dead code rather than bringing it back through ifdefs. Although, I did leave in the comment for the `getParams` :
```c++
// do not clear params in case adding to an existing set
```
Although, I can always delete that as well. The HCP slip system still has these in here and I would say would be a good example for people to look at if they want to build off our slip system classes. If we want to parameterize the BCC and FCC classes later on the logic being used here is pretty simple and should be easy enough to re-add.

**Review by nrbarton — APPROVED** [review]

**Comment by rcarson3** [comment]
Thanks @nrbarton for looking this over. I just did a double check with the nvcc compiler to make sure we weren't missing anything thrown up when compiling on the gpu and things looked good there. So, I'll go ahead and merge this branch.
