### PR TITLE
CMake fixes related to CUDA

### LINKED ISSUE #10: Older Nvidia cards (Compute Capability 6X) dieing during start-up
Ran into this issue on my consumer 1070 card that I have using cuda 10.1.243 a long time ago, and it seems like one of our collabs is running into the same issue with a different card which has a similar compute capability. It would be nice if we could figure this out so people could run on this cards.

I'll update this later with the exact error, but it was pretty generic error about a memory issue even while running small problems.

### PR DESCRIPTION
**Pull request by rcarson3**
Should have caught some of these issues with #16 but I failed to compile the submodule version of snls with cuda. Additionally, I should have caught the python bindings failing to build with cuda.

So, this PR does 2 things. First, it updates the version of SNLS to the one given here: https://github.com/LLNL/SNLS/pull/8 . Next, it updates the python bindings and their cmake compilation, so we don't run into the issue with where on a build with cuda enabled things the python bindings don't error out because RAJA realizes it was built with cuda.

A future PR will introduce CI testing which should catch this sort of thing from happening in the future...

This PR closes #10 as well. Although, I would like a better solution in the future for it.

### CODE REVIEW

File: pyecmech/ecmech_classes.hpp [hunk 1]
```diff
@@ -412,16 +414,25 @@ class pyEvptn_norm : public pyevptn_base
 
 };
 
+typedef ecmech::KineticsKMBalD<true, false, false, false, 1> Kin_KMBalD_TFF;
```
Comment (nrbarton) [inline pyecmech/ecmech_classes.hpp]: Why add all of these typedefs here rather than using them from ECMech_cases.h?

Comment (rcarson3) [reply pyecmech/ecmech_classes.hpp]: So, I unfortunately can't use them when the library is built with cuda or else we get a number of build errors when the final python file is being built :( 

Now, if we split up the case file into two where one had all the non-cuda/gpu specific typedefs in, and then the other file imported that one and had cuda/gpu type things we could make use of the case file. However, the current issue is the raja foralls in evptnWrap are depend on a few raja defines which know whether or not things should be compiled with cuda or not :/

Comment (nrbarton) [reply pyecmech/ecmech_classes.hpp]: Hmm... I do not follow the details, but that is okay. I see how that you had mentioned this code duplication issue elsewhere -- I was triaging things in somewhat haphazard fashion today. Maybe just add a comment about the undesirable code duplication and the motivation for it. Something to help people (or yourself later down the line) who come across this and might be confused.

**Review by nrbarton — APPROVED** [review]
Should be good once you consider adding a comment to let people know the motivation for the code duplication.

File: pyecmech/ecmech_classes.hpp (hunk 1 above)
Comment (rcarson3) [reply pyecmech/ecmech_classes.hpp]: I think I've figured out a way to avoid the code duplication and avoid the build failing during the last portion of the python module creation, but I won't get to it until Friday.

**Comment by rcarson3** [comment]
@nrbarton I re-did some stuff that fixed the code duplication part if you'd like to take a look.

Additionally, I figured out a fix for #10 that I figured I'd include here as its small. You can see the relevant code changes for that in d13eaf00c29f3bc42ff9a5de387b25c191f3a6b4 . It's not the most elegant solution as I wanted our CORAL1 machines to not take a 20-25% performance hit, but it works for the time being. I'll probably see if I can't come up with a better solution that makes use of `chai` though to just transfer the class memory over once to the GPU as I believe that's whats happening with the CORAL1 machines...

**Comment by nrbarton** [comment]
Thanks for taking a look at the code duplication thing. Those recent changes look fine to me.
